### PR TITLE
Introduces a JRuby development environment

### LINKED ISSUE #13: Provide documentation for integrating and testing dspace-jruby with DSpace
This will be necessary in order to proceed with refactoring both https://github.com/pulibrary/dspace-jruby and https://github.com/pulibrary/dspace-cli

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #13

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
The test failures are a false negative, this is due to the fact that the base image used by Molecule has `/usr/share/man/` directories removed (please see https://github.com/pulibrary/ubuntubionicimage/blob/dockerimage/Dockerfile#L15), yielding `error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory` when attempting to install packages (please see https://app.circleci.com/pipelines/github/pulibrary/dspace-development/62/workflows/5ab9b6dc-6729-4c15-a2b3-ce67fece01c1/jobs/145)

**Comment by jrgriffiniii** [comment]
The `README` does not provide instructions for installation Maven with `brew install maven`

**Comment by jrgriffiniii** [comment]
References to `jrgriffiniii` in the README should be changed to `pulibrary` for working with Docker images.

**Comment by jrgriffiniii** [comment]
The README should contain instructions for installing Docker on macOS.

**Comment by jrgriffiniii** [comment]
The README should document the usage of `source ./scripts/docker_provision_local_storage.sh --start-at-task="my ansible task"`

**Comment by jrgriffiniii** [comment]
When running `irb` as the `pulsys` user in Docker, there are file system permissions issues which must be resolved with the following: `chmod a+w -R /dspace/log`. Attempting to restrict access by just adding `pulsys` to the owning user group did *not* prove effective.

Further, `irb` should be invoked as `irb -I /usr/local/src/jruby-projects/dspace-jruby/lib`

**Comment by jrgriffiniii** [comment]
A general outline for working with IRB should be added to the README:

```
pulsys@7ef9e5aeb441:/usr/local/src/dspace-jruby$ irb -I /usr/local/src/dspace-jruby/lib
irb(main):001:0> require 'dspace'
=> true
irb(main):002:0> DSpace.load
Using /dspace
Loading jars
Loading /dspace/config/dspace.cfg
INFO: Loading provided config file: /dspace/config/dspace.cfg
INFO: Using dspace provided log configuration (log.init.config)
INFO: Loading: /dspace/config/log4j.properties
Starting new DSpaceKernel
DB jdbc:postgresql://localhost:5432/dspace, UserName=dspace, PostgreSQL Native Driver
=> true
irb(main):003:0> DSpace.login('admin@localhost')
=> nil
irb(main):004:0> person = DEPerson.find('admin@localhost')
=> #<Java::OrgDspaceEperson::EPerson:0x6dca31eb>
```

**Comment by jrgriffiniii** [comment]
The runlevel for the `postgresql` service needs to be adjusted for cases where the Docker Container is stopped.

**Comment by kmcelwee** [comment]
I ended up creating the following `irbd` and `jrubyd` aliases which may be useful

```bash
alias irbd=“irb -I /usr/local/src/jruby-projects/dspace-jruby/lib -I /usr/local/src/jruby-projects/dspace-cli”
alias jrubyd=“jruby -I /usr/local/src/jruby-projects/dspace-jruby/lib -I /usr/local/src/jruby-projects/dspace-cli”
```

**Comment by jrgriffiniii** [comment]
This should be ready to be merged. Unfortunately, the runlevel issue is actually due to the fact that the base image for the Docker container does not have `systemd` installed. SysVinit is instead used, and attempting to install `systemd` atop of this requires a reboot (one cannot really support this for a Docker provisioning pipeline).

**Comment by jrgriffiniii** [comment]
I am going to move to close this until we decide when (and if) it might be worth returning to exploring the development of a DSpace 5.x Docker environment.

**Pull request closed without merging**
